analyzer:
  errors:
    unnecessary_overrides: ignore
    constant_identifier_names: ignore
    non_constant_identifier_names: ignore
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    
