// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQwagNuBsvpNKUMT83fvdgMOmi5LykvU',
    appId: '1:1091533121926:web:8170f34a5775f7a35ea407',
    messagingSenderId: '1091533121926',
    projectId: 'aqqair-145b2',
    authDomain: 'aqqair-145b2.firebaseapp.com',
    storageBucket: 'aqqair-145b2.firebasestorage.app',
    measurementId: 'G-HNHJ5CRCG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUvzIqBEPm5cpFGM442CiVO1ColKwyZV4',
    appId: '1:1091533121926:android:bf5bc4dca529e97d5ea407',
    messagingSenderId: '1091533121926',
    projectId: 'aqqair-145b2',
    storageBucket: 'aqqair-145b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7a4jHiTc3bVqEKCsbWAZIAHn9gt-0U5E',
    appId: '1:1091533121926:ios:eb5c9f61ef090c305ea407',
    messagingSenderId: '1091533121926',
    projectId: 'aqqair-145b2',
    storageBucket: 'aqqair-145b2.firebasestorage.app',
    iosBundleId: 'AaqaqirTirganin.aaqaqirTirganin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7a4jHiTc3bVqEKCsbWAZIAHn9gt-0U5E',
    appId: '1:1091533121926:ios:eb5c9f61ef090c305ea407',
    messagingSenderId: '1091533121926',
    projectId: 'aqqair-145b2',
    storageBucket: 'aqqair-145b2.firebasestorage.app',
    iosBundleId: 'AaqaqirTirganin.aaqaqirTirganin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkQwagNuBsvpNKUMT83fvdgMOmi5LykvU',
    appId: '1:1091533121926:web:7427c689dfe9b3425ea407',
    messagingSenderId: '1091533121926',
    projectId: 'aqqair-145b2',
    authDomain: 'aqqair-145b2.firebaseapp.com',
    storageBucket: 'aqqair-145b2.firebasestorage.app',
    measurementId: 'G-VR6Z9317WQ',
  );
}
